apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-node
  labels:
    app: centos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
      - name: centos
        image: centos:latest
        command: ["sleep", "100000000"]
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "500m"
            memory: 500Mi
        volumeMounts:
        - mountPath: /sharedvol
          name: sharedvol
      volumes:
        - name: sharedvol
          persistentVolumeClaim:
            claimName: master-vol

