apiVersion: apps/v1
kind: Deployment
metadata:
  name: ursa
  labels:
    app: ursa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ursa
  template:
    metadata:
      labels:
        app: ursa
    spec:
      containers:
      - name: ursa
        image: ubuntu:latest
        command: ["sleep", "infinity"]
        ports:
        - containerPort: 22
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "500m"
            memory: 500Mi
        volumeMounts:
        - mountPath: /sharedvol
          name: sharedvol
      volumes:
        - name: sharedvol
          persistentVolumeClaim:
            claimName: master-vol
---
apiVersion: v1
kind: Service
metadata:
  name: ursa-connect
  labels:
    run: ursa-connect
spec:
  ports:
  - port: 22
  selector:
    run: ursa-connect
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ursa-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ursa
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

